"""empty message

Revision ID: 0ac30c75d49d
Revises: 
Create Date: 2019-05-28 12:55:32.536499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac30c75d49d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastodon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admins', sa.Column('domain', sa.String(), nullable=True))
    op.create_foreign_key(None, 'admins', 'servers', ['domain'], ['domain'])
    op.add_column('servers', sa.Column('last_notified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'last_notified')
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.drop_column('admins', 'domain')
    op.drop_table('mastodon')
    # ### end Alembic commands ###
