"""create web_domain

Revision ID: 800b65046cc2
Revises: b79381179732
Create Date: 2023-02-10 08:41:32.504624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800b65046cc2'
down_revision = 'b79381179732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('web_domain', sa.String(), nullable=True))
    # ### end Alembic commands ###

    t_servers = sa.Table(
        'servers',
        sa.MetaData(),
        sa.Column('domain', sa.String()),
        sa.Column('web_domain', sa.String()),
    )

    connection = op.get_bind()
    results = connection.execute(sa.select([
        t_servers.c.domain,
        t_servers.c.web_domain,
    ])).fetchall()

    for domain, _web_domain in results:
        connection.execute(
            sa.update(t_servers)
            .where(t_servers.c.domain == domain)
            .values(web_domain=domain)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'web_domain')
    # ### end Alembic commands ###
