"""add update type

Revision ID: e861e7d38f07
Revises: 0ac30c75d49d
Create Date: 2019-06-10 01:07:15.710822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e861e7d38f07'
down_revision = '0ac30c75d49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('admins', sa.Column('update_type', sa.Enum('ALL', 'STABLE', name='updatetype', native_enum=False), default='stable', nullable=False))
    op.execute('alter table "admins" add column "update_type" varchar(6) not null default \'stable\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'update_type')
    # ### end Alembic commands ###
